### PR TITLE
Upgrade appcenter-cli version to 2.7.3

### PR DESCRIPTION
**Pull request by xom9ikk**
Description of the problem:
---------
Error `500` appears when trying to download apk to AppCenter.

Proposed solution:
----------
In technical support, I was advised to update the appcenter-cli version to version `2.7.0+.`

Changes:
----------
`appcenter-cli` version has been updated to `2.7.3`

### CODE REVIEW

**Comment by wzieba** [comment]
Hi @xom9ikk , thanks for the PR - I indeed confirm that the action stopped working, here's test run on `master`: https://github.com/wzieba/AppCenter-Github-Action/actions/runs/407765600. 

Let's merge it and see if it starts to work

**Comment by wzieba** [comment]
Works fine after your PR: https://github.com/wzieba/AppCenter-Github-Action/runs/1516057049?check_suite_focus=true

Thank you 🎉

**Comment by xom9ikk** [comment]
@wzieba , I'm very glad that this action worked. As the time will be - please update the release and publish it on the marketplace 😄

**Comment by wzieba** [comment]
The release has been pushed and updated on the marketplace. Thanks again for the PR!

https://github.com/wzieba/AppCenter-Github-Action/releases/tag/v1.3.2
https://github.com/marketplace/actions/app-center

**Pull request merged**
