### PR TITLE
Support for multiple distribution groups

### PR DESCRIPTION
**Pull request by okalman**
divider character is semicolon

### CODE REVIEW

**Comment by tmorone-rezi** [comment]
This would be useful to have. Will you consider merging this?

**Comment by wzieba** [comment]
@okalman @tmorone-rezi sorry for delay, I've missed that.

Yes, this sounds like a nice feature. I'm surprised that `appcenter-cli` doesn't have multiple distribution groups implemented, [like firebase-cli does](https://firebase.google.com/docs/app-distribution/android/distribute-cli).

@okalman can I ask you to rebase this PR and write some small note to the `README.md` file to emphasize that with this action it's possible to distribute to multiple groups? Thanks in advance. If you don't have time, please leave a note and I'll handle it.

**Comment by okalman** [comment]
sure, I'll handle it later today

**Comment by okalman** [comment]
@wzieba done

**Comment by wzieba** [comment]
Thank you @okalman!

**Pull request merged**
